--!strict
-- NavettePartBData - Util Script for Rive
-- Vertices: 472
-- Polygons: 337

local NavettePartBData = {}

NavettePartBData.vertices = {
  { -1.2915, 1.0924, 0.765 },
     -- {"etc..."},
  { 4.8722, 2.1687, -0.0447 },
}

NavettePartBData.faces = {
  { verts = { 17, 18, 41, 38 }, c = 1 },
  { verts = { 28, 125, 127, 30 }, c = 3 },
  { verts = { 13, 14, 37, 34 }, c = 1 },
      -- {"etc..."},
  { verts = { 410, 436, 453, 418 }, c = 3 },
}

return NavettePartBData
