--!strict
-- NavettePartCData - Util Script for Rive
-- Vertices: 426
-- Polygons: 337

local NavettePartCData = {}

NavettePartCData.vertices = {
  { 5.5104, 2.9693, 0.1565 },
     -- {"etc..."},
  { 2.5163, 1.1289, -0.4309 },
}

NavettePartCData.faces = {
  { verts = { 1, 28, 78, 40 }, c = 3 },
      -- {"etc..."},
  { verts = { 377, 399, 400, 417, 416, 396, 397, 379 }, c = 1 },
  { verts = { 371, 380, 381, 373 }, c = 1 },
  { verts = { 386, 387, 389, 388 }, c = 3 },
}

return NavettePartCData
