--!strict
-- NavettePartDData - Util Script for Rive
-- Vertices: 414
-- Polygons: 337

local NavettePartDData = {}

NavettePartDData.vertices = {
  { 0.4667, 1.7449, 0.8517 },
  -- {"etc..."},
  { -2.6859, 1.1289, -0.0468 },
}
-- 337 faces
NavettePartDData.faces = {
  { verts = { 25, 26, 22, 21 }, c = 3 }, -- 337 faces
    -- {"etc..."},
  { verts = { 292, 294, 296, 298, 300, 302, 304, 290 }, c = 4 },
    -- {"etc..."},
}

return NavettePartDData
