--!strict
-- NavettePartAData - Util Script for Rive
-- Vertices: 442
-- Polygons: 337

local NavettePartAData = {}

NavettePartAData.vertices = {
  { 1.2915, 1.0924, 0.765 },
      -- {"etc..."},
  { 0.0, -3.5235, 0.3971 },
}

NavettePartAData.faces = {
  { verts = { 34, 9, 20, 44 }, c = 3 },
  { verts = { 28, 37, 1, 5 }, c = 1 },
  { verts = { 35, 2, 1, 37 }, c = 1 },
  { verts = { 154, 149, 366, 369 }, c = 1 },
  { verts = { 156, 377, 366, 149 }, c = 1 },
      -- {"etc..."},
  { verts = { 383, 375, 335, 363 }, c = 1 },
}

return NavettePartAData
